export const GENRE_REPOSITORY = 'GENRE_REPOSITORY';
export const VIDEO_REPOSITORY = 'VIDEO_REPOSITORY';
export const PLAYLIST_REPOSITORY = 'PLAYLIST_REPOSITORY';
export const STORAGE_SERVICE = 'STORAGE_SERVICE';
export const ELASTICSEARCH_CLIENT = 'ELASTICSEARCH_CLIENT';
